version: '3'
services:
  mydbos1:
    image: mysql:5.6
    volumes:
      - mysql_storage_new2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: vandana
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb1

  joomlaos:
    image: joomla
    restart: always
    depends_on:
      - mydbos1
    ports:
      - 8081:80
    environment:

      JOOMLA_DB_HOST: mydbos1
      JOOMLA_DB_USER: vandana
      JOOMLA_DB_PASSWORD: redhat
      JOOMLA_DB_NAME: mydb1

    volumes:
      - hp_storage_new:/var/www/html
   

volumes:
  hp_storage_new:
  mysql_storage_new2:

